### ISSUE TITLE
Metodologia

### ISSUE THREAD

**Issue by tayh** [Desenho1-2018/FGA-The-Endless-Game#6]
Criar documento descrevendo a metodologia escolhida pelo grupo

**Comment by manueng** [comment]
Metodologia 
      Metodologia disciplina e método como o software é produzido no tocante a gestão de trabalho, formalização dos processos e 
      A metodologia de desenvolvimento e a cascata ,gwp , ela tem como desvantagens o teste tardio do software ,  dificuldade na realização de mudanças . (scrum).
    O framework de desenvolvimento scrum vem para tentar solucionar esses problemas ele fase faz uso de sprints com duração definida , times auto-gerenciáveis (scrum)
     O scrum busca construir uma visão compartilhada do projeto , o que casa muito bem com o desenvolvimento de um trabalho em grupo. (Scrum).
    Ele faz uso de inspeções frequentes para possibilitar um melhor mapeamento desde de o início. E tomada de medidas corretivas para evitar maiores problemas . (Scrum).
 O scrum apresenta uma série de papéis , product owner,maximização do trabalho da equipe e entrega do produto desejado . Equipe de de desenvolvimento responsável pelo desenvolvimento do software e scrum master , líder da equipe de desenvolvimento . Responsável pela gestão da equipe de desenvolvimento. ( empresa de desenvolvimento de jogos).  
    O scrum apresenta como artefatos product backlog , lista de funcionalidades a serem entregues e das melhorias a serem realizadas. Ele apresenta uma periodização dos artefatos a serem entregues .  Sprint backlog , parte do product backlog , que será desenvolvida na sprint.  ( empresa de desenvolvimento de jogos).
     O scrum busca tirar proveito da desorganização característica do processo de desenvolvimento de software.( empresa de desenvolvimento de jogos).
   A metodologia kanban faz uso de cartões para permitir a modelagem visual do processo produtivo . Ele também não estipula quais tarefas serão realizadas num dado período como faz o scrum . (Sjoberg,D , Solberg ,A 2012 ).
  Ele foi utilizado pela primeira vez em 2004 num projeto da microsoft . Ele se adequa melhor em cenários mais imprevisíveis como , por ser o menos rígido dentre as metodologias de desenvolvimento. O scrum devido a sua rigidez  apresenta dificuldades para escalar, além de um maior tempo de desenvolvimento(Sjoberg,D , Solberg ,A 2012 ).
          


     empresa de desenvolvimento de jogos scrum 
acessado dia 26 de  março ás 17:25.  disponível em:                    
Docplayer.com.br/131462-O-uso-de-metodo-scrum-emempresas-de-desenvolvimento-de-software-de-jogos.html

scrum -considerações sobre o desenvolvimento de jogos por meio do framework scrum . 
 quantifying the effect of using kanban versus scrum.  Solberg, A. Sjoberg, D.  acessado dia 27 de março de 2018 às 21:43 disponível em: http://ieeexplore.ieee.org/document/6231615/?reload=true
 o Nosso utilizara entao os timeoxes do scrum , assim como sprints , e reuniões semanais para tratar da avaliação do projeto , assim como utilizara  o zenhub como uma ferramenta visual para fazer  acompanhamento de tarefas.

**Comment by manueng** [comment]
[](https://docs.google.com/document/d/1zmTlx9DnG1mhNI3ei8XTLyQEa5av33TlIrgqO8UPBxk/edit)
