### ISSUE TITLE
Plano de Gestão

### ISSUE THREAD

**Issue by tayh** [Desenho1-2018/FGA-The-Endless-Game#9]
No Plano de Gestão constam os seguintes sub-tópicos:

Plano de Escopo
Plano de Tempo
Plano de Custos
Plano de Recursos Humanos
Plano de Comunicações
Plano de Riscos
Plano de Partes Interessadas

**Comment by kleberbritomoreira10** [comment]
Vou fazer os dois primeiros planos: plano de escopo, plano de tempo.
Alguem pega o 3 e o 4: plano de custos e plano de recursos humanos.
E a outra pessoa o 5 e o 7: plano de comunicações e plano das partes interessadas

**Comment by manueng** [comment]
ok vou pegar o plano de comunicacao e o plano de recursos humanos.

**Comment by manueng** [comment]
foi mal galera nao percebi que estava selecionado para outras pessoas.

**Comment by manueng** [comment]
nao fiz nao
